---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgDJO1705LCCuAGpvvJpVi+yf8+AwBnJ3FIdTSiIZlnzf+amro1It5YjyBBzZnY1IH2CjM76O3lfbgx9rFz1SofBFvzX2cYlWw1AZsLm7g9iYppOpLUITxv9jjjYWqlKJdytF5aQ3Qr6hhp2X4uEOTGvEX5hUaVg6CTHhu9ciPS28BA2dCFmgd5sfqQzgP+j09zyZ6eyayITKRTfi3lCoORxmBCm9731JRfYjRdim9hasbo2382tvnXoe55wLuVLIdJ+DY7oeXqXFR62Xcc5wp4vwGkqtv49JKyx7g4ABrJdl6Z/WhaKqs2Tp3WkLrRaX7QAPdwMhjy3mKbOaG8zppXKDT4zDHEDWRmTdcfFOplXKE6TQwBwwfsAtBZrrHUrEaWJzkwbvL+KY3FKgVzlT4U2udczHlmGOTLPoJbJ4Jgr7jPk3WCv0f6u69fFWD/BgRHQIBE9eKIW7FJgH+XTY5adOXyCJXjFP5v4G3X9tk8mKUF5jK9S+YfsugbV34RiNh6xa0CYaCAyO8yMbcNwEfgDVfFQsXkQzkhvhfsb2dbBt6GVSeAV3Ui/LGuRcGXuJa6EufMOfVNoXtpVFu/MBbbCouEXq66Iw3FFrtyqp6TLZ3Ezd/Jl8RmEcpeYWBJ3mK4IKLBlXVUBk7uSFbGx6nkl6Mm9N4hhbTVuWCsReBNmYlSb1buXplPM1O6YKVlF3QftAOp2hGUEEvwKgDIoB5z4FLtM4R35TFRTW9uV8+rZAP85930ugEM9PspcX5BlMQEvQ2GfaMxc19kLCBKRcKN70SvybA==
  template:
    metadata:
      name: backend-secrets
      namespace: default
