---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAdXQ3FIJo9DVwcsi4Jk4rdhB2M7QcU9Y43IUJQi54nr/NG2krUPw9kmglbsHARFIJzOgP/ree0PkCQu6suwq/vangeCMZ2VSILQOg1p4yim2qXTjbW20PL4I7ASaJ4zOUe9bDKGCxoWGbnoI64nSdLRqem0Db5N3rudCP3iB59F4QSnzcJrYgeSAl4NE9dKsgibBTn/l6JMjqe5meN6VCkxquxmg7JFDZjmLQ0d1IvtCZvaM5I9Pqrr5yuS8K5pNooVZrIPV3UFt7e4Jz7F4hwsgHqrH+l/LdZaTDZdPd1mXy3PaKcSNp5kyuwR92Tr406Yx1q6+h6ZT1sQdgCzQqXInmFkQdCMc4yU97lGKSvhKhkUFMN4/8rntM7WyokwZxpwS/9hfpSvqX9EJfQAgpZicmimFQ5tXA2oHl2xgZ3wADgrpbuEPxg2lMsKgYubG4+uaCcgz2scNIJ1+tBFLlY1Co9TnSxjKM0Qn6woK959PkH4bAA7bPEj1MkLPJSeZBH5ptWWkyX5RtyZ1mKHRzGJIOSvhLFJAk+OTrydwDwrlXGMZnruEcgvEDVMZbPQypACesfDbiz/b8lC2sfaeKRJfOiJcaOzUvEg1t0K8Mu7Sz3QuxzhbQpZFwCJdZVYGzAsohIa6KiRLlF0fI/fp6Y4GVr6Q6VgHuu0I2K5QTV94mFvbR577gb2x5YOc3RywTpZUZcGdrGf3NA
    MONGO_INITDB_ROOT_USERNAME: AgADkLHSXXB4v0JQUqP05hvMz7hEBC4w8DtSAWkeI1OOGuwKsnuVhSdIhZDfsnj5842QyHmnP7f1uFTtwEuo3j+rLdkIAnR9zdOLrkrQ3Gdty65BenBZegNpLnIoieT1yuzcSO/IXofJP9Mjerhh/Lcqr3b4vVzvmPmPZJNA830PxksKWFUuA7AJGsNEZ+o1Gab+k7lN94BPt9eAPgTukIPA10B1qyHQOx8J2bdREOZ6Eup1kT7ser1pUexG+2E0FW0LsfGaRvARoDWmWU/ECLGC510hO4i29pnp/0Ph2MODBq4vuKAxmYUjbCykrF3PEjeylY55NFfHGOs+M4lBxtDene994gW95T+ATuobWgde/AKvyH0Aowe8Ku0cuirZ22solcKl4qrfNn1yoPFe8WWmxe1+dHN/ZAJSiH+UeJoNmzeDoV53OYCYJkXjgpSFLk/v1QPVVgML0VlnkngCFYWzWxoCkXmp+2KQMJFpGX5Y+GYLegr1/cjN99lbxNFhsKPSC6gEXGAFvxfKtG0jsSsPtfamnqxxEOwn0bhyPsBEazV74Rpi1IwPy75zNsGulLeniez/9p64zbgL98qiN8siWqrEGjgEu/oxUSJp2YahbWFeGO/LflEcBdeQsq6pMble4XtONYuctJMz4IEIB/S/ueLjkNXNHSS9Wg92tWy8FWy3ggGLwzvonxwZReTMupY/Q0M8hQ==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
